services:
  keybr:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./.local/state/keybr:/home/node/.local/state/keybr
      - ./.env:/etc/keybr/env
    ports:
      - 30044:3000
    restart: unless-stopped
